server:
  port: 8080

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: mall-ai-service
        uri: lb://mall-ai-service
        predicates:
          - Path=/api/ai/**

      - id: mall-biz-service
        uri: lb://mall-biz-service
        predicates:
          - Path=/api/biz/**, /api/auth/**, /api/admin/**

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
    - name: 业务微服务
      url: /api/biz/v3/api-docs
      context-path: /api