server:
  port: 8080

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${HOST_IP:host.docker.internal}:8848
    gateway:
      routes:
      - id: mall-ai-service
        uri: lb://mall-ai-service
        predicates:
          - Path=/api/ai/**

      - id: mall-biz-service
        uri: lb://mall-biz-service
        predicates:
          - Path=/api/biz/**, /api/auth/**, /api/admin/**, /api/chat/**

      - id: static-files
        uri: http://minio:9000/
        predicates:
          - Path=/static/**
        filters:
        - StripPrefix=1

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
    - name: 业务微服务
      url: /api/biz/v3/api-docs
      context-path: /api
    - name: AI微服务
      url: /api/ai/v3/api-docs
      context-path: /api/ai