server:
  port: 0
  servlet:
    context-path: /api/ai
    multipart:
      max-file-size: 15MB
      max-request-size: 150MB

spring:
  application:
    name: mall-ai-service
  cloud:
    nacos:
      discovery:
        server-addr: ${HOST_IP:host.docker.internal}:8848
  datasource:
    url: "jdbc:mysql://${HOST_IP:host.docker.internal}:3306/emall?de"
    username: ${MYSQL_NAME}
    password: ${MYSQL_PSWD}
  data:
    redis:
      host: redis
      port: 6379
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${DS_KEY}
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.8
      embedding:
        base-url: https://api.siliconflow.cn
        api-key: ${SF_KEY}
        options:
          model: BAAI/bge-m3
    vectorstore:
      milvus:
        initialize-schema: true
        embedding-dimension: 1024
        client:
          host: milvus

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

minio:
  endpoint: http://minio:9000
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}